[package]
name = "raytracer"
version = "0.1.0"
edition = "2021"

[dependencies]
glam ={ version = "*"}
indicatif = { version ="0.17.8", features = ["rayon"]}
itertools = {version = "*"}
rand = "0.8.5"
rayon = "1.10.0"
enum_dispatch = {version = "0.3.13"}